Allow psr/cache v3.0
jonahgeorge/jaeger-client-php pull request #125
Opened 2022-07-21 08:45 UTC by avrphp

2022-07-21 09:15 UTC, sergeyklay requested changes

2022-07-21 09:15 UTC, sergeyklay commented on composer.json
> +        "psr/cache": "^1.0 || ^2.0" || ^3.0",
```suggestion
        "psr/cache": "^1.0 || ^2.0 || ^3.0",
```

2022-07-21 09:17 UTC, sergeyklay commented
@avrphp Could you please fix mentioned typo, and also this branch has conflicts that must be resolved. Could you rebase?

2022-07-21 10:04 UTC, avrphp commented
@sergeyklay done

2022-07-21 13:25 UTC, sergeyklay approved these changes
Looks good to me. Thank you for contributing!

2022-07-21 13:25 UTC, merged

2022-07-26 21:55 UTC, sergeyklay commented
Just released new version: https://github.com/jonahgeorge/jaeger-client-php/releases/tag/v1.4.3